### ISSUE TITLE
Grid breakpoint issues

### ISSUE THREAD

**Issue by ChrisHomsey** [trouble/react-css-grid#2]
Hey all,

I've been testing the grid system out a bit and I've run into a few bugs every now and then.

Biggest issue seems to be that my defined breakpoints are ignored. I've noticed that sometimes the media queries in the generated CSS seem to be out of order– for instance, I'll get the large breakpoint styling overriding the medium breakpoint styling when my viewport is clearly a medium size.

Heres one I'm currently seeing. I've set my breakpoints for a grid below:

<img width="210" alt="Screen Shot 2020-01-18 at 5 37 50 PM" src="https://user-images.githubusercontent.com/17804979/72671539-2276e780-3a1a-11ea-93ad-9a9d6610bd6d.png">

I then notice that the large breakpoint grid layout does not go into effect until 993px. Sure enough, when I inspected the cell element, I see that the css media query is set to 992px.

<img width="297" alt="Screen Shot 2020-01-18 at 5 39 55 PM" src="https://user-images.githubusercontent.com/17804979/72671563-71248180-3a1a-11ea-9501-151ba73f0fde.png">

It seems that maybe thats a default breakpoint that you guys might have in the code. I haven't checked the src yet. As you can see, there is a media query that matches my defined break point a little lower– but it seems to precede the 992px query, which overrides it.

I really like the developer experience of this grid system though. Keep it up!

**Comment by jacobsfletch** [comment]
Hey @ChrisHomsey!

I see you have `hCount={6}` defined on your `GridProvider`, with `hSpanL={9}` on the nested `Cell` (inferring this based on the classes in your stylesheet). This would definitely cause unexpected behavior, since the `Cell` is trying to span 9 but only 6 are available. My suspicion is that your screenshots are out of sync, though, since no classes would even be generated outside of the provided `hCount`.

**BUT** this is a secondary observation and doesn't directly respond to your issue -- for that I'll need to see your entire setup (`GridProvider`, `Grid`, and `Cell`) so that I can reproduce it on my end (or even a CodeSandbox that I could poke around with).

☮️

**Comment by ChrisHomsey** [comment]
Hey @jacobsfletch. Heres a the entire setup. This isn't nested in any other @trbl/react-css-grid components. Looks like the `{9}` may be coming down from the parent `<Cell />`, oddly.

<img width="320" alt="Screen Shot 2020-01-19 at 7 35 58 PM" src="https://user-images.githubusercontent.com/17804979/72708094-f9487b00-3b2f-11ea-90d1-b4a6ba319192.png">

`{serviceGrid}` then maps into these Cells:

<img width="240" alt="Screen Shot 2020-01-20 at 2 55 12 AM" src="https://user-images.githubusercontent.com/17804979/72708332-7b38a400-3b30-11ea-861e-fe4ae12998ff.png">

**Comment by jacobsfletch** [comment]
@ChrisHomsey 

Ahhh, this clears some things up. I think we can get this in working order for you just by modifying your setup.

There should be only one single, top-level instance of the `GridProvider` within your app. There's no need to nest any additional `GridProvider` beyond this (**note:** each instance of the `Grid` component will actually inject a `GridProvider` behind-the-scenes for you).

So from there it's pretty simple, you just need to render a `Grid` each time you'd like to use `Cell`. The only rule here is that a `Cell` cannot be a descendent of another `Cell` without a `Grid` somewhere between them. **Note:** a `Cell` _does not_ have to be an immediate child of a `Grid`.

To see this in action, there are three working demos in the source code that you can reference: [here](https://github.com/trouble/react-css-grid/blob/master/demo/Grid1.demo.js), [here](https://github.com/trouble/react-css-grid/blob/master/demo/Grid2.demo.js), and [here](https://github.com/trouble/react-css-grid/blob/master/demo/Grid3.demo.js).

^^^ Much of this stems from a lack of documentation...that will be coming down the pipeline!

👾

**Comment by jacobsfletch** [comment]
@ChrisHomsey 

Any luck here?

**Comment by ChrisHomsey** [comment]
Hey Jacob, I just realized I never responded and closed this. January was a wild month!

Thanks for all your help. You ended up pointing me in the right direction. Because I needed different grid layouts within the same app, I ended up using the scopeCSSTo prop and everything was great after that!

**Comment by jacobsfletch** [comment]
💥
